---
AWSTemplateFormatVersion: '2010-09-09'
Transform: CfnGitSync
Parameters:
  RepositoryOwner:
    Type: String
  RepositoryName: Type String
Resources:
  InitialPlaceholder:
    Type: AWS::CloudFormation::WaitConditionHandle
  DevMainStack:
    Type: CfnGitSync::Stack
    Properties:
      RepositoryOwner: "!Ref RepositoryOwner"
      RepositoryName: "!Ref RepositoryName"
      BranchName: main
      StackName: dev-main
      StackDeploymentFile: stacks/environments/dev/ap-southeast-2/main.stack.yaml
