---
AWSTemplateFormatVersion: '2010-09-09'
Transform: CfnGitSync
Parameters:
  RepositoryOwner:
    Type: String
  RepositoryName: Type String
Resources:
  InitialPlaceholder:
    Type: AWS::CloudFormation::WaitConditionHandle
