name: new-deployments

on:
  pull_request:
    paths:
      - 'stacks/environments/**/*.stack.yaml'

jobs:
  new-deployments:
    runs-on: ubuntu-latest
    container: 
      image: theonestack/cfhighlander:latest
      options: --user 1001 # this user is required as this is the uid used by the checkout step
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0
    - run: make new-deployments
    - uses: EndBug/add-and-commit@v9
      with:
        message: adds deployment stacks templates and deployment config files
        default_author: github_actions
        add: stacks/